from odoo import fields, models

# Must match stored DB values on crm.lead x_studio_visa_program
VISA_PROGRAM_SELECTION = [
    ('ANTIGUA (donation)', 'ANTIGUA (donation)'),
    ('ANTIGUA (property)', 'ANTIGUA (property)'),
    ('AU 132B', 'AU 132B'),
    ('AU 186', 'AU 186'),
    ('AU 188A', 'AU 188A'),
    ('AU 188B', 'AU 188B'),
    ('AU 188C', 'AU 188C'),
    ('AU 188C EXTENSION STREAM', 'AU 188C EXTENSION STREAM'),
    ('AU 188E', 'AU 188E'),
    ('AU 461 (NZ citizen)', 'AU 461 (NZ citizen)'),
    ('AU 482', 'AU 482'),
    ('AU 482 SBS', 'AU 482 (SBS)'),
    ('AU 482 SELF-EMPLOYED', 'AU 482 (self employed)'),
    ('AU 482 STREAM', 'AU 482 STREAM'),
    ('AU 485', 'AU 485'),
    ('AU 485 STREAM', 'AU 485 STREAM'),
    ('AU 500 STUDENT VISA', 'AU 500 (student visa)'),
    ('AU 600 (visitor)', 'AU 600 (visitor)'),
    ('AU 888', 'AU 888'),
    ('AU CITIZENSHIP', 'AU CITIZENSHIP'),
    ('AU FAMILY', 'AU FAMILY'),
    ('AU GTI', 'AU GTI'),
    ('AU HK STREAM (189)', 'AU HK STREAM (189)'),
    ('AU HK STREAM (191)', 'AU HK STREAM (191)'),
    ('AU MINT', 'AU MINT'),
    ('AU NIV', 'AU NIV'),
    ('AU NIV (P2 Empowered)', 'AU NIV (P2 Empowered)'),
    ('AU NIV (P2)', 'AU NIV (P2)'),
    ('AU RRV', 'AU RRV'),
    ('AU SKILLED', 'AU SKILLED'),
    ('BULGARIA', 'BULGARIA'),
    ('CA (rehabilitation)', 'CA REHABILITATION'),
    ('CA AIP', 'CA AIP'),
    ('CA AOS', 'CA AOS'),
    ('CA BUSINESS', 'CA BUSINESS'),
    ('CA CITIZENSHIP', 'CA CITIZENSHIP'),
    ('CA ETA', 'CA ETA'),
    ('CA FAMILY', 'CA FAMILY'),
    ('CA ICT', 'CA ICT'),
    ('CA OPEN WORK PERMIT', 'CA OPEN WORK PERMIT'),
    ('CA PNP', 'CA PNP'),
    ('CA PNP ENTREPRENEUR', 'CA PNP (entrepreneur)'),
    ('CA QUEBEC INVESTMENT', 'CA QUEBEC INVESTMENT'),
    ('CA SELF-EMPLOYED', 'CA SELF-EMPLOYED'),
    ('CA SKILLED', 'CA SKILLED'),
    ('CA STREAM A', 'CA STREAM A'),
    ('CA STREAM B', 'CA STREAM B'),
    ('CA STREAM B (LMIA)', 'CA STREAM B (LMIA)'),
    ('CA STUDY PERMIT', 'CA STUDY PERMIT'),
    ('CA SUV', 'CA SUV'),
    ('CA SUV (TEAM)', 'CA SUV (TEAM)'),
    ('CA SUV CONSULTING', 'CA SUV CONSULTING'),
    ('DOMINICA', 'DOMINICA'),
    ('DUBAI', 'DUBAI'),
    ('EDUCATION', 'EDUCATION'),
    ('GREECE', 'GREECE'),
    ('GRENADA (donation)', 'GRENADA (donation)'),
    ('GRENADA (property)', 'GRENADA (property)'),
    ('HK GEP', 'HK GEP'),
    ('HK 優秀人才入境計劃', 'HK 優秀人才入境計劃'),
    ('HK 受養人來港居留簽證', 'HK 受養人來港居留簽證'),
    ('HK 永居', 'HK 永居'),
    ('HK 留學', 'HK 留學'),
    ('HK 資本投資者入境計劃', 'HK 資本投資者入境計劃'),
    ('HK 輸入內地人材計劃', 'HK 輸入內地人材計劃'),
    ('HK 輸入勞工計劃', 'HK 輸入勞工計劃'),
    ('HK 高才(A類)續簽', 'HK 高才(A類)續簽'),
    ('HK 高才(B類)續簽', 'HK 高才(B類)續簽'),
    ('HK 高才(C類)續簽', 'HK 高才(C類)續簽'),
    ('HK 高端人才通行證(A類)計劃', 'HK 高端人才通行證(A類)計劃'),
    ('HK 高端人才通行證(B類)計劃', 'HK 高端人才通行證(B類)計劃'),
    ('HK 高端人才通行證(C類)計劃', 'HK 高端人才通行證(C類)計劃'),
    ('INSURANCE', 'INSURANCE'),
    ('IRELAND DONATION', 'IRELAND DONATION'),
    ('IRELAND INVESTMENT', 'IRELAND INVESTMENT'),
    ('JP SUV 4+1', 'JP SUV 4+1'),
    ('JP 經營者管理', 'JP 經營者管理'),
    ('JP 高度人才 (技術)', 'JP 高度人才 (技術)'),
    ('JP 高度人才 (經營管理)', 'JP 高度人才 (經營管理)'),
    ('LATVIA', 'LATVIA'),
    ('MALAYSIA', 'MALAYSIA'),
    ('MALTA', 'MALTA'),
    ('MM2H', 'MY MM2H'),
    ('NAURU', 'NAURU'),
    ('NON-IMMIGRATION', 'NON-IMMIGRATION'),
    ('NZ ACTIVE INVESTOR PLUS VISA (BALANCED)', 'NZ ACTIVE INVESTOR PLUS VISA (BALANCED)'),
    ('NZ ACTIVE INVESTOR PLUS VISA (GROWTH)', 'NZ ACTIVE INVESTOR PLUS VISA (GROWTH)'),
    ('NZ AIP (balanced)', 'NZ AIP (balanced)'),
    ('NZ AIP (growth)', 'NZ AIP (growth)'),
    ('NZ ARV', 'NZ ARV'),
    ('NZ BIV', 'NZ BIV'),
    ('NZ CRITICAL PURPOSE VISITOR', 'NZ CRITICAL PURPOSE VISITOR'),
    ('NZ FAMILY', 'NZ FAMILY'),
    ('NZ GREEN LIST', 'NZ GREEN LIST'),
    ('NZ INVESTOR', 'NZ INVESTOR'),
    ('NZ INVESTOR 2', 'NZ INVESTOR 2'),
    ('NZ SKILLED', 'NZ SKILLED'),
    ('OTHER VISAS', 'OTHER VISAS'),
    ('PORTUGAL CITIZENSHIP BY DECENT', 'PORTUGAL CITIZENSHIP BY DECENT'),
    ('PORTUGAL FUND', 'PORTUGAL FUND'),
    ('PORTUGAL OTHERS', 'PORTUGAL OTHERS'),
    ('PROPERTY', 'PROPERTY'),
    ('SINGAPORE EP', 'SG EP'),
    ('ST KITTS', 'ST KITTS'),
    ('ST KITTS DONATION', 'ST KITTS DONATION'),
    ('TAX', 'TAX'),
    ('TBD', 'TBD'),
    ('TBD (failed to contact)', 'TBD (failed to contact)'),
    ('TURKEY (deposit)', 'TURKEY (deposit)'),
    ('TURKEY (fund)', 'TURKEY (fund)'),
    ('TURKEY (property)', 'TURKEY (property)'),
    ('UK BNO', 'UK BNO'),
    ('UK BNO (application)', 'UK BNO (application)'),
    ('UK BNO APPLICATION', 'UK BNO APPLICATION'),
    ('UK BUSINESS', 'UK BUSINESS'),
    ('UK CITIZENSHIP', 'UK CITIZENSHIP'),
    ('UK FAMILY', 'UK FAMILY'),
    ('UK GLOBAL TALENT', 'UK GLOBAL TALENT'),
    ('UK ILR', 'UK ILR'),
    ('UK T1 INVESTOR', 'UK T1 INVESTOR'),
    ('UK TIER-1 ENT', 'UK TIER-1 ENT'),
    ('UN INVESTOR', 'UN INVESTOR'),
    ('US EB-1A', 'US EB-1A'),
    ('US EB-2', 'US EB-2'),
    ('US EB-3', 'US EB-3'),
    ('US EB-5', 'US EB-5'),
    ('US FAMILY', 'US FAMILY'),
    ('US L-1A', 'US L-1A'),
    ('VANUATU', 'VANUATU'),
]

# Must match stored DB values on crm.lead x_studio_previous_visa_program
PREVIOUS_VISA_PROGRAM_SELECTION = [
    ('ANTIGUA (donation)', 'ANTIGUA (donation)'),
    ('ANTIGUA (property)', 'ANTIGUA (property)'),
    ('AU 132B', 'AU 132B'),
    ('AU 186', 'AU 186'),
    ('AU 188B', 'AU 188B'),
    ('AU 188C', 'AU 188C'),
    ('AU 188R', 'AU 188E'),
    ('AU 461 (NZ citizen)', 'AU 461 (NZ citizen)'),
    ('AU 482', 'AU 482'),
    ('AU 482 (SBS)', 'AU 482 (SBS)'),
    ('AU 482 (self employed)', 'AU 482 (self employed)'),
    ('AU 482 STREAM', 'AU 482 STREAM'),
    ('AU 485', 'AU 485'),
    ('AU 485 STREAM', 'AU 485 STREAM'),
    ('AU 500', 'AU 500 (student visa)'),
    ('AU 600 (visitor)', 'AU 600 (visitor)'),
    ('AU CITIZENSHIP', 'AU CITIZENSHIP'),
    ('AU FAMILY', 'AU FAMILY'),
    ('AU GTI', 'AU GTI'),
    ('AU MINT', 'AU MINT'),
    ('AU NIV', 'AU NIV'),
    ('AU NIV (P2 Empowered)', 'AU NIV (P2 Empowered)'),
    ('AU NIV (P2)', 'AU NIV (P2)'),
    ('AU RRV', 'AU RRV'),
    ('AU SKILLED', 'AU SKILLED'),
    ('BULGARIA', 'BULGARIA'),
    ('CA (self employed)', 'CA (self employed)'),
    ('CA AIP', 'CA AIP'),
    ('CA BUSINESS', 'CA BUSINESS'),
    ('CA CITIZENSHIP', 'CA CITIZENSHIP'),
    ('CA ETA', 'CA ETA'),
    ('CA FAMILY', 'CA FAMILY'),
    ('CA ICT', 'CA ICT'),
    ('CA OPEN WORK PERMIT', 'CA OPEN WORK PERMIT'),
    ('CA PNP', 'CA PNP'),
    ('CA PNP (entrereneur)', 'CA PNP (entrepreneur)'),
    ('CA QIIP', 'CA QIIP'),
    ('CA QUEBEC INVESTMENT', 'CA QUEBEC INVESTMENT'),
    ('CA REHABILITATION', 'CA REHABILITATION'),
    ('CA SELF-EMPLOYED', 'CA SELF-EMPLOYED'),
    ('CA SKILLED', 'CA SKILLED'),
    ('CA STREAM A', 'CA STREAM A'),
    ('CA STREAM B', 'CA STREAM B'),
    ('CA STREAM B (LMIA)', 'CA STREAM B (LMIA)'),
    ('CA STUDY PERMIT', 'CA STUDY PERMIT'),
    ('CA SUV', 'CA SUV'),
    ('CA SUV (team)', 'CA SUV (team)'),
    ('DOMINICA', 'DOMINICA'),
    ('DUBAI', 'DUBAI'),
    ('EDUCATION', 'EDUCATION'),
    ('GREECE', 'GREECE'),
    ('GRENADA (donation)', 'GRENADA (donation)'),
    ('GRENADA (property)', 'GRENADA (property)'),
    ('HK GEP', 'HK GEP'),
    ('HK 優秀人才入境計劃', 'HK 優秀人才入境計劃'),
    ('HK 受養人來港居留簽證', 'HK 受養人來港居留簽證'),
    ('HK 永居', 'HK 永居'),
    ('HK 留學', 'HK 留學'),
    ('HK 資本投資者入境計劃', 'HK 資本投資者入境計劃'),
    ('HK 輸入內地人材計劃', 'HK 輸入內地人材計劃'),
    ('HK 輸入勞工計劃', 'HK 輸入勞工計劃'),
    ('HK 高端人才通行證(A類)計劃', 'HK 高端人才通行證(A類)計劃'),
    ('HK 高端人才通行證(B類)計劃', 'HK 高端人才通行證(B類)計劃'),
    ('HK 高端人才通行證(C類)計劃', 'HK 高端人才通行證(C類)計劃'),
    ('INSURANCE', 'INSURANCE'),
    ('IRELAND DONATION', 'IRELAND DONATION'),
    ('IRELAND INVESTMENT', 'IRELAND INVESTMENT'),
    ('JP SUV 4+1', 'JP SUV 4+1'),
    ('JP 經營者管理', 'JP 經營者管理'),
    ('JP 高度人才 (技術)', 'JP 高度人才 (技術)'),
    ('JP 高度人才 (經營管理)', 'JP 高度人才 (經營管理)'),
    ('LATVIA', 'LATVIA'),
    ('MALAYSIA', 'MALAYSIA'),
    ('MALTA', 'MALTA'),
    ('MY MM2H', 'MY MM2H'),
    ('NAURU', 'NAURU'),
    ('NON-IMMIGRATION', 'NON-IMMIGRATION'),
    ('NZ ACTIVE INVESTOR PLUS VISA (BALANCED)', 'NZ ACTIVE INVESTOR PLUS VISA (BALANCED)'),
    ('NZ AIP (balanced)', 'NZ AIP (balanced)'),
    ('NZ AIP (growth)', 'NZ AIP (growth)'),
    ('NZ ARV', 'NZ ARV'),
    ('NZ BIV', 'NZ BIV'),
    ('NZ BUSINESS', 'NZ BUSINESS'),
    ('NZ CRITICAL PURPOSE VISITOR', 'NZ CRITICAL PURPOSE VISITOR'),
    ('NZ FAMILY', 'NZ FAMILY'),
    ('NZ GREEN LIST', 'NZ GREEN LIST'),
    ('NZ SKILLED', 'NZ SKILLED'),
    ('OTHER VISAS', 'OTHER VISAS'),
    ('OTHERS', 'OTHERS'),
    ('PORTUGAL FUND', 'PORTUGAL FUND'),
    ('PORTUGAL OTHERS', 'PORTUGAL OTHERS'),
    ('PROPERTY', 'PROPERTY'),
    ('SG EP', 'SG EP'),
    ('SINGAPORE EP', 'SINGAPORE EP'),
    ('SPAIN', 'SPAIN'),
    ('ST KITTS', 'ST KITTS'),
    ('TAX', 'TAX'),
    ('TBD', 'TBD'),
    ('TURKEY (PROPERTY)', 'TURKEY (property)'),
    ('TURKEY (deposit)', 'TURKEY (deposit)'),
    ('TURKEY (fund)', 'TURKEY (fund)'),
    ('UK BNO', 'UK BNO'),
    ('UK BNO (application)', 'UK BNO (application)'),
    ('UK BNO APPLICATION', 'UK BNO APPLICATION'),
    ('UK BUSINESS', 'UK BUSINESS'),
    ('UK CITIZENSHIP', 'UK CITIZENSHIP'),
    ('UK FAMILY', 'UK FAMILY'),
    ('UK GLOBAL TALENT', 'UK GLOBAL TALENT'),
    ('UK ILR', 'UK ILR'),
    ('UK INVESTOR', 'UK INVESTOR'),
    ('UK T1 (entrepreneur)', 'UK T1 (entrepreneur)'),
    ('UK T1 INVESTOR', 'UK T1 (investor)'),
    ('US EB-1A', 'US EB-1A'),
    ('US EB-2', 'US EB-2'),
    ('US EB-3', 'US EB-3'),
    ('US EB-5', 'US EB-5'),
    ('US FAMILY', 'US FAMILY'),
    ('US L-1A', 'US L-1A'),
    ('VANUATU', 'VANUATU'),
]

# Must match stored DB values on crm.lead x_studio_background
BACKGROUND_SELECTION = [
    ('Administrative', 'Arts, entertainment and recreation'),
    ('Agriculture, forestry and fishing', 'Renewables and low emission technologies'),
    ('Businessman', 'Top-of-field'),
    ('Construction', 'Financial Services and FinTech'),
    ('Electricity and gas supply', 'Education'),
    ('Entrepreneur', 'Entrepreneur'),
    ('Financial and insurance activities', 'Health Industries'),
    ('HNW', 'High Net Worth'),
    ('Holders of PhDs', 'Holders of PhDs'),
    ('Information and communications', 'Critical Technologies'),
    ('Investor', 'Recipients of national research grants'),
    ('Manufacturing', 'Defence Capabilities and Space'),
    ('Mining and quarrying', 'Agri-food and AgTech'),
    ('Others', 'Others'),
    ('Professional, scientific and technical activities', 'Infrastructure and Transport'),
    ('Real estate activities', 'Real estate activities'),
]


class ResPartner(models.Model):
    _inherit = 'res.partner'

    # Fields that exist in Opportunity but not in Contact
    visa_program = fields.Selection(
        VISA_PROGRAM_SELECTION,
        string='Visa Program',
    )
    previous_visa_program = fields.Selection(
        PREVIOUS_VISA_PROGRAM_SELECTION,
        string='Previous Visa Program',
    )
    background = fields.Selection(
        BACKGROUND_SELECTION,
        string='Background',
    )
    business_owner_or_management_grade = fields.Char(
        string='Business Owner / Management Grade',
    )
    b2b_engagement = fields.Boolean(
        string='B2B Engagement',
    )
    higher_diploma_or_above = fields.Char(
        string='Higher Diploma or Above',
    )
